In [1]:
import numpy as np
import math

a = np.array([[0,1,2],[3,4,5],[6,7,8]])

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
print(a[0])

[0 1 2]


In [13]:
b = np.array([[0,0,0],[0,3,0],[0,6,0],[1.5,0,-3],[1.5,0,3],[-3,0,2]])
c = np.array([(b[1]-b[0]),(b[2]-b[0]),(b[3]-b[1]),(b[4]-b[1]),(b[5]-b[2])])

print(c)

def absval(x):
    y = [0]*len(x)
    for i in range(len(x)):
        y[i] = np.linalg.norm(c[i])
    
    return y

print("abs = ",absval(c))

[[ 0.   3.   0. ]
 [ 0.   6.   0. ]
 [ 1.5 -3.  -3. ]
 [ 1.5 -3.   3. ]
 [-3.  -6.   2. ]]
abs =  [3.0, 6.0, 4.5, 4.5, 7.0]
