In [1]:
import numpy as np
import math

a = np.array([[0,1,2],[3,4,5],[6,7,8]])

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
print(a[0])

[0 1 2]


In [3]:
points = np.array([[0,0,0],[0,3,0],[0,6,0],[1.5,0,-3],[1.5,0,3],[-3,0,2]])
vectors = np.array([(points[1]-points[0]),(points[2]-points[0]),(points[3]-points[1]),(points[4]-points[1]),(points[5]-points[2])])
print("Vectors =\n",vectors)

def vecNorm(x):
    y = [0]*len(x)
    for i in range(len(x)):
        y[i] = np.linalg.norm(x[i])
    return y

normals = vecNorm(vectors)
print("Normals =",normals)

def vecUnits(x):
    y = np.array(x)
    for i in range(len(x)):
        y[i] = x[i]/np.linalg.norm(x[i])
    return y

units = vecUnits(vectors)
print("Unit Vectors =\n",units)

Vectors =
 [[ 0.   3.   0. ]
 [ 0.   6.   0. ]
 [ 1.5 -3.  -3. ]
 [ 1.5 -3.   3. ]
 [-3.  -6.   2. ]]
Normals = [3.0, 6.0, 4.5, 4.5, 7.0]
Unit Vectors =
 [[ 0.          1.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.33333333 -0.66666667 -0.66666667]
 [ 0.33333333 -0.66666667  0.66666667]
 [-0.42857143 -0.85714286  0.28571429]]


In [4]:
BD = np.cross(vectors[0],units[2])
BE = np.cross(vectors[0],units[3])
CF = np.cross(vectors[1],units[4])

print(BD)
print(BE)
print(CF)

[-2.  0. -1.]
[ 2.  0. -1.]
[ 1.71428571 -0.          2.57142857]


In [35]:
from sympy import symbols, Eq, solve

Tcf = 455
Tbd, Tbe, Ax, Ay, Az = symbols('Tbd Tbe Ax Ay Az')
Mx = Eq(Tbd*BD[0]+Tbe*BE[0]+Tcf*CF[0], 0)
My = Eq(Tbd*BD[1]+Tbe*BE[1]+Tcf*CF[1], 0)
Mz = Eq(Tbd*BD[2]+Tbe*BE[2]+Tcf*CF[2], 0)
Fx = Eq(Tbd*units[2][0]+Tbe*units[3][0]+Tcf*units[4][0]+Ax, 0)
Fy = Eq(Tbd*units[2][1]+Tbe*units[3][1]+Tcf*units[4][1]+Ay, 0)
Fz = Eq(Tbd*units[2][2]+Tbe*units[3][2]+Tcf*units[4][2]+Az, 0)
T = solve((Mx, My, Mz, Fx, Fy, Fz), (Tbd, Tbe, Ax, Ay, Az))
Tbd = T[Tbd]
Tbe = T[Tbe]
Ax = T[Ax]
Ay = T[Ay]
Az = T[Az]

reaction = np.array([Ax,Ay,Az])
print(reaction)

[-195.000000000000 1170.00000000000 130.000000000000]


Determining Static Equilibrium in NumPY

What you'll do:
    In this tutorial, we will use NumPy to create vectors and moments using NumPy arrays
    
What you'll learn:
    -How to represent points, vectors, and moments in NumPy.
    -How to find the normal of vectors
    
What you'll need:
    -NumPy
    -SymPy

In [6]:
# import numpy as np
# from sympy import symbols, Eq, solve

In this tutorial we will use the following NumPy tools:
    -np.linalg.norm : this function determines the normal of a vector